/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
//package FormsPrincipais;

import java.awt.Color;

/**
 *
 * @author Rafael
 */
public class FormLogin extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    JanelaPrincipal grafico;

    public FormLogin(JanelaPrincipal grafico) {
        this.grafico = grafico;
        initComponents();

    }

    public JanelaPrincipal getGrafico() {
        return grafico;
    }

    public void setGrafico(JanelaPrincipal grafico) {
        this.grafico = grafico;
    }

    public void setUser(String user, String pass) {
        TB_username.setText(user);
        TB_password.setText(pass);
        if (user.compareTo("") != 0) {
            jCBremember.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogIn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TB_username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCBremember = new javax.swing.JCheckBox();
        btnLogin = new javax.swing.JButton();
        btnCriarUser = new javax.swing.JButton();
        TB_password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        lbaviso = new javax.swing.JLabel();

        jLabel5.setText("Username");

        TB_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TB_usernameActionPerformed(evt);
            }
        });

        jLabel6.setText("Password");

        jCBremember.setText("Lembrar Utilizador");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnCriarUser.setText("Criar User");
        btnCriarUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCriarUserMouseClicked(evt);
            }
        });
        btnCriarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLogInLayout = new javax.swing.GroupLayout(PanelLogIn);
        PanelLogIn.setLayout(PanelLogInLayout);
        PanelLogInLayout.setHorizontalGroup(
            PanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogInLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(PanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(PanelLogInLayout.createSequentialGroup()
                        .addGroup(PanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLogInLayout.createSequentialGroup()
                                .addComponent(jCBremember)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLogin))
                            .addComponent(TB_username, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCriarUser))
                    .addComponent(TB_password, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(605, Short.MAX_VALUE))
        );
        PanelLogInLayout.setVerticalGroup(
            PanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLogInLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TB_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TB_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(PanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBremember)
                    .addComponent(btnLogin)
                    .addComponent(btnCriarUser))
                .addGap(476, 476, 476))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sueca ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbaviso, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelLogIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(PanelLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbaviso, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarUserActionPerformed
        //jogo.enviaMensagem("nick", 2, null);

        //jogo.enviaMensagem("nick", 2, null);
        if (TB_username.getText().isEmpty()) {
            lbaviso.setText("Introduza um username");
            lbaviso.setForeground(Color.red);
            return;
        }
        if (TB_password.getText().isEmpty()) {
            lbaviso.setText("Introduza uma password");
            lbaviso.setForeground(Color.red);
            return;
        }

        if (grafico.getComunicacao().getServer() == null) {
            grafico.getComunicacao().createSocket();
            if (grafico.getComunicacao().getServer() == null) {
                lbaviso.setText("Servidor nao encontrado. Tente mais tarde");
                lbaviso.setForeground(Color.red);
                return;
            }
        }
        grafico.getComunicacao().CriarUser(TB_username.getText(), TB_password.getText());
        if (grafico.getComunicacao().isSucesso()) {
            grafico.getComunicacao().setUser(TB_username.getText());
            grafico.getchatRoom().setLbusername();
            grafico.showfChatRoom();
            grafico.getComunicacao().start();
        } else {
            lbaviso.setText("Utilizador já Registado");
            lbaviso.setForeground(Color.red);
        }
        if (jCBremember.isSelected()) {
            grafico.getOp().addUser(TB_username.getText(), TB_password.getText());
        }



    }//GEN-LAST:event_btnCriarUserActionPerformed

    private void btnCriarUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCriarUserMouseClicked
    }//GEN-LAST:event_btnCriarUserMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        if (TB_username.getText().isEmpty()) {
            lbaviso.setText("Introduza um username");
            lbaviso.setForeground(Color.red);
            return;
        }
        if (TB_password.getText().isEmpty()) {
            lbaviso.setText("Introduza uma password");
            lbaviso.setForeground(Color.red);
            return;
        }
        if (grafico.getComunicacao().getServer() == null) {
            grafico.getComunicacao().createSocket();
            if (grafico.getComunicacao().getServer() == null) {
                lbaviso.setText("Servidor nao encontrado. Tente mais tarde");
                lbaviso.setForeground(Color.red);
                return;
            }
        }
        grafico.getComunicacao().Login(TB_username.getText(), TB_password.getText());
        if (grafico.getComunicacao().isSucesso()) {
            grafico.getComunicacao().setUser(TB_username.getText());
            grafico.showfChatRoom();
            grafico.getComunicacao().start();
        } else {
            lbaviso.setText("Login ou password errados");
            lbaviso.setForeground(Color.red);
        }
        if (jCBremember.isSelected()) {
            grafico.getOp().addUser(TB_username.getText(), TB_password.getText());
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    private void TB_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TB_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TB_usernameActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLogIn;
    private javax.swing.JPasswordField TB_password;
    private javax.swing.JTextField TB_username;
    private javax.swing.JButton btnCriarUser;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox jCBremember;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbaviso;
    // End of variables declaration//GEN-END:variables
}
