/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ParteGrafica;

import java.awt.Dimension;

/**
 *
 * @author Rafael
 */
public class FormInicio extends javax.swing.JPanel {

    /**
     * Creates new form popup
     */
    
    JanelaNovoJogo popup;
    String[][] jogadores;

    public FormInicio(JanelaNovoJogo popup) {
        this.popup = popup;
        initComponents();
        Dimension size = new Dimension(310, 300);
        setPreferredSize(size);
        setSize(size);
        jogadores = new String[0][0];
    }

    public JanelaNovoJogo getPopup() {
        return popup;
    }

    public void setPopup(JanelaNovoJogo popup) {
        this.popup = popup;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListJogadores = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListJogosDisp = new javax.swing.JList();
        BtnJoin = new javax.swing.JButton();
        BtnNewGame = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(310, 300));
        setMinimumSize(new java.awt.Dimension(310, 300));

        jLabel1.setText("Jogos Disponiveis");

        jLabel2.setText("Jogadores");

        ListJogadores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(ListJogadores);

        ListJogosDisp.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListJogosDisp.setToolTipText("");
        ListJogosDisp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListJogosDispMouseClicked(evt);
            }
        });
        ListJogosDisp.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListJogosDispValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListJogosDisp);

        BtnJoin.setText("Entrar");
        BtnJoin.setEnabled(false);
        BtnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJoinActionPerformed(evt);
            }
        });

        BtnNewGame.setText("Novo Jogo");
        BtnNewGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnNewGameMouseClicked(evt);
            }
        });
        BtnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNewGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnNewGame)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnJoin)
                    .addComponent(BtnNewGame))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel2)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNewGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNewGameMouseClicked
    }//GEN-LAST:event_BtnNewGameMouseClicked

    private void BtnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJoinActionPerformed
        //Entrar num jogo

        //popup.showfListaEspera();

        //TODO: enviar mensagem ao servidor
        popup.getChatRoom().getGrafico().getComunicacao().JoinJogo(ListJogosDisp.getSelectedValue().toString());
        popup.Update();

    }//GEN-LAST:event_BtnJoinActionPerformed

    private void BtnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNewGameActionPerformed


        //popup.showfListaEspera();

        //TODO: enviar mensagem ao servidor
        popup.getChatRoom().getGrafico().getComunicacao().CriarJogo(null);//null-nome do jogo ainda não implementado
        // popup.Update();
        // popup.getFormListaEspera1().updateJogadores();
    }//GEN-LAST:event_BtnNewGameActionPerformed

    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag);
        //BtnJoin.setEnabled(false);
    }

    private void ListJogosDispValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListJogosDispValueChanged
        ListJogadores.removeAll();
        if (ListJogosDisp.getSelectedIndex() >= 0) {
            ListJogadores.setListData(jogadores[ListJogosDisp.getSelectedIndex()]);
            BtnJoin.setEnabled(true);
        } else {
            BtnJoin.setEnabled(false);
        }
    }//GEN-LAST:event_ListJogosDispValueChanged

    private void ListJogosDispMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListJogosDispMouseClicked
    }//GEN-LAST:event_ListJogosDispMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnJoin;
    private javax.swing.JButton BtnNewGame;
    private javax.swing.JList ListJogadores;
    private javax.swing.JList ListJogosDisp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public void UpdateListaJogos(String[][] idJogoUser) {//
        if (idJogoUser == null) {
            return;
        }

        ListJogosDisp.removeAll();
        ListJogadores.removeAll();
        if (idJogoUser.length <= 0) {
            return;
        }

        String[] aux = new String[idJogoUser.length];
        jogadores = new String[idJogoUser.length][];
        for (int i = 0; i < idJogoUser.length; i++) {
            aux[i] = idJogoUser[i][0];
            jogadores[i] = new String[idJogoUser[i].length];
            for (int j = 1; j < idJogoUser[i].length; j++) {
                jogadores[i][j - 1] = idJogoUser[i][j];
            }
        }
        ListJogosDisp.setListData(aux);
        //ListJogosDisp.setSelectedIndex(0);
    }

}
