/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ParteGrafica;

import java.awt.Dimension;
import java.util.ArrayList;

/**
 *
 * @author Rafael
 */
public class FormInvite extends javax.swing.JPanel {

    /**
     * Creates new form FormInvite
     */
    JanelaNovoJogo popup;
    private ArrayList<String> JogadoresConvidados;
    private ArrayList<String> JogadoresAceites;

    public FormInvite(JanelaNovoJogo popup) {
        this.popup = popup;
        JogadoresConvidados = new ArrayList<>();
        JogadoresAceites = new ArrayList<>();
        initComponents();
        Dimension size = new Dimension(380, 360);
        setSize(size);
        setPreferredSize(size);
        BtnComecar.setVisible(false);
    }

    public ArrayList<String> getJogadoresConvidados() {
        return JogadoresConvidados;
    }

    public void setJogadoresConvidados(ArrayList<String> JogadoresConvidados) {
        this.JogadoresConvidados = JogadoresConvidados;
    }

    public ArrayList<String> getJogadoresAceites() {
        return JogadoresAceites;
    }

    public void setJogadoresAceites(ArrayList<String> JogadoresAceites) {
        this.JogadoresAceites = JogadoresAceites;
    }

    public void update() {
        ListaJogadoresAprovados.removeAll();
        ListaJogadoresConvidados.removeAll();

        ListaJogadoresAprovados.setListData(JogadoresAceites.toArray());
        ListaJogadoresConvidados.setListData(JogadoresConvidados.toArray());

        ListaJogadoresAprovados.repaint();
        ListaJogadoresConvidados.repaint();
        if (JogadoresAceites.isEmpty()) {
            return;
        }
        if (JogadoresAceites.get(0).equals(popup.getChatRoom().getGrafico().getComunicacao().getUser())) {
            BtnComecar.setVisible(true);
            BtnCancelar.setText("Cancelar");
        } else {
            BtnComecar.setVisible(false);
            BtnCancelar.setText("Sair");
        }
    }

    public boolean isAceitesEmpty() {
        return JogadoresAceites.isEmpty();
    }

    public void addConvidado(String convidado) {
        JogadoresConvidados.add(convidado);
    }

    public void addAceite(String aceite) {
        JogadoresAceites.add(aceite);
    }

    public void removeConvidado(String convidado) {
        JogadoresConvidados.remove(convidado);
    }

    public void removeAceite(String aceite) {
        JogadoresAceites.remove(aceite);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaJogadoresAprovados = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaJogadoresConvidados = new javax.swing.JList();
        BtnComecar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(380, 360));
        setMinimumSize(new java.awt.Dimension(380, 360));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(380, 360));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Jogadores Aprovados");

        ListaJogadoresAprovados.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ListaJogadoresAprovados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(ListaJogadoresAprovados);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Jogadores Convidados");

        ListaJogadoresConvidados.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ListaJogadoresConvidados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(ListaJogadoresConvidados);

        BtnComecar.setText("Começar");
        BtnComecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComecarActionPerformed(evt);
            }
        });

        BtnCancelar.setText("Sair");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnComecar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnComecar)
                    .addComponent(BtnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void BtnComecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComecarActionPerformed
        popup.getChatRoom().getGrafico().getComunicacao().inviteStartJogo();
    }//GEN-LAST:event_BtnComecarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        popup.getChatRoom().getGrafico().getComunicacao().inviteCancelar();
        popup.showfInicio();
    }//GEN-LAST:event_BtnCancelarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnComecar;
    private javax.swing.JList ListaJogadoresAprovados;
    private javax.swing.JList ListaJogadoresConvidados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
