/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ParteGrafica;

import java.awt.Graphics;

/**
 *
 * @author Rafael
 */
public class Pontuacao extends javax.swing.JPanel {

    /**
     * Creates new form Pontuacao
     */
    private static final int ESPESSURA = 3;
    private static final int ALTURA = 25;
    private int espacamento1;
    private int espacamento2;
    private int pontos1;
    private int pontos2;
    private Graphics g1;
    private Graphics g2;

    public Pontuacao() {
        initComponents();
        setLocation(0, 0);
        espacamento1 = 0;
        espacamento2 = 0;
        pontos1 = 0;
        pontos2 = 0;
        g1 = null;
        g2 = null;
        //PontosEquipa1.setIgnoreRepaint(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        PontosEquipa1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PontosEquipa2 = new javax.swing.JPanel();

        javax.swing.GroupLayout PontosEquipa1Layout = new javax.swing.GroupLayout(PontosEquipa1);
        PontosEquipa1.setLayout(PontosEquipa1Layout);
        PontosEquipa1Layout.setHorizontalGroup(
            PontosEquipa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PontosEquipa1Layout.setVerticalGroup(
            PontosEquipa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Equipa1:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Equipa2:");

        javax.swing.GroupLayout PontosEquipa2Layout = new javax.swing.GroupLayout(PontosEquipa2);
        PontosEquipa2.setLayout(PontosEquipa2Layout);
        PontosEquipa2Layout.setHorizontalGroup(
            PontosEquipa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PontosEquipa2Layout.setVerticalGroup(
            PontosEquipa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PontosEquipa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PontosEquipa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PontosEquipa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PontosEquipa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    static int num;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PontosEquipa1;
    private javax.swing.JPanel PontosEquipa2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public void addPont(int eq, int n) {
        if (eq == 1) {
            pontos1 += n;
            Pontua1();
        }
        if (eq == 2) {
            pontos2 += n;
            Pontua2();
        }
    }

    @Override
    public void repaint() {
        super.repaint();

    }
@Override
public void paintComponent(Graphics g) {
    super.paintComponent(g);
    Pontua1();
    Pontua2();
}
    
    
    public void Pontua1() {
        if (g1 == null) {
            g1 = PontosEquipa1.getGraphics();
        }
        for (int i = 0; i < ESPESSURA; i++) {
            if (pontos1 % 5 != 0) {
                g1.drawLine(5 + espacamento1 + pontos1 * 5 + i, 4, 5 + espacamento1 + pontos1 * 5 + i, 4 + ALTURA);
            } else {

                g1.drawLine((5 + espacamento1 + (pontos1 + 1) * 5) - 6 * 5 + i, 4 + ALTURA, 5 + espacamento1 + pontos1 * 5 + i, 4);
            }
        }
        if (pontos1 % 5 == 0) {
            espacamento1 += 4;
        }
    }

    public void Pontua2() {
        if (g2 == null) {
            g2 = PontosEquipa2.getGraphics();
        }
        for (int i = 0; i < ESPESSURA; i++) {
            if (pontos2 % 5 != 0) {
                g2.drawLine(5 + espacamento2 + pontos2 * 5 + i, 4, 5 + espacamento2 + pontos2 * 5 + i, 4 + ALTURA);
            } else {

                g2.drawLine((5 + espacamento2 + (pontos2 + 1) * 5) - 6 * 5 + i, 4 + ALTURA, 5 + espacamento2 + pontos2 * 5 + i, 4);
            }
        }
        if (pontos2 % 5 == 0) {
            espacamento2 += 4;
        }
    }
}
